import {StyleSheet} from 'react-native';
import {
  widthPercentageToDP as wp,
  heightPercentageToDP as hp,
} from 'react-native-responsive-screen';

export default StyleSheet.create({
  container: {flex: 1, backgroundColor: '#fafafa'},
  header: {
    width: wp(100),
    height: hp(10),
    backgroundColor: '#FFFFFF',
    shadowColor: '#D1D0CE',
    shadowOpacity: 4,
    elevation: 15,
    flexDirection: 'row',
  },
  headerText: {
    color: '#000000',
    fontSize: hp(3.4),
    fontFamily: 'Poppins-Medium',
    fontWeight: '600',
    marginTop: hp(3.2),
    marginLeft: wp(8),
  },
  mobileNumberText: {
    fontSize: hp(1.9),
    fontFamily: 'Gilroy-Bold',
    marginTop: hp(7.8),
    marginLeft: wp(6),
    color: '#00192F',
    opacity: 0.5,
  },
  mobileText: {
    fontSize: 10,
    fontFamily: 'Rubik-Bold',
    marginTop: 30,
    marginLeft: 25,
    color: 'rgba(12, 26, 52, 0.64)',
    opacity: 0.5,
  },
  primaryButton: {
    width: wp(33),
    height: hp(5.2),
    backgroundColor: '#0084F8',
    marginLeft: wp(5),
    borderRadius: hp(12),
    marginTop: hp(4),
  },
  primaryText: {
    alignSelf: 'center',
    marginTop: hp(1.4),
    color: '#FFFFFF',
    fontFamily: 'Poppins-Bold',
    fontSize: hp(1.5),
  },
  supportText: {
    fontSize: hp(1.5),
    fontFamily: 'Poppins-Medium',
    fontWeight: '500',
    marginTop: hp(5),
    marginLeft: wp(44),
    color: '#0084F8',
  },
  otpView: {
    marginHorizontal: wp(16),
    justifyContent: 'space-around',
    alignItems: 'center',
    flexDirection: 'row',
    marginTop: hp(4.6),
    marginLeft: wp(6),
  },
  boxView: {
    borderRadius: hp(1.4),
    borderColor: '#EBEBEB',
    backgroundColor: '#EBEBEB',
    width: wp(11.4),
    height: hp(5.4),
  },
  input: {
    alignSelf: 'center',
    marginLeft: wp(2.2),
    marginTop: hp(0.6),
    color: '#4B4545',
    fontFamily: 'Rubik-Medium',
    fontSize: hp(2),
    fontWeight: '500',
  },
  resendText: {
    color: '#0084F8',
    fontSize: hp(1.3),
    fontFamily: 'Poppins-Bold',
    marginLeft: wp(10),
    marginTop: hp(4.8),
  },
  footerText: {
    fontSize: hp(1.2),
    width: wp(86),
    fontFamily: 'Gilroy-SemiBold',
    color: '#0C1A34',
    fontWeight: '600',
    opacity: 0.56,
    marginTop: hp(54),
    alignSelf: 'center',
  },
  innerContainer: {flex: 1},
});
