import {StyleSheet} from 'react-native';
import {
  widthPercentageToDP as wp,
  heightPercentageToDP as hp,
} from 'react-native-responsive-screen';

export default StyleSheet.create({
  container: {flex: 1, backgroundColor: 'white'},
  header: {
    width: wp(100),
    height: hp(12),
    backgroundColor: '#FFFFFF',
    shadowColor: '#D1D0CE',
    shadowOpacity: 4,
    elevation: 30,
    flexDirection: 'row',
  },
  headerText: {
    color: '#000000',
    fontSize: hp(3.2),
    fontFamily: 'Poppins-Medium',
    fontWeight: '600',
    marginTop: hp(5),
    marginLeft: wp(7),
  },
  supportText: {
    fontSize: hp(1.4),
    fontFamily: 'Poppins-Medium',
    fontWeight: '500',
    marginTop: hp(6),
    marginLeft: wp(40),
    color: '#0084F8',
  },
  registerText: {
    color: '#667686',
    fontFamily: 'Gilroy-Bold',
    fontWeight: '600',
    fontSize: hp(1.4),
    marginTop: hp(5),
    letterSpacing: 1,
    marginLeft: wp(7),
  },
  borderLine: {
    width: wp(100),
    borderWidth: hp(0.1),
    borderColor: 'rgba(0, 0, 0, 0.1)',
    opacity: 0.5,
    marginTop: hp(3.6),
  },
  nameText: {
    color: '#00192F',
    fontFamily: 'Gilroy-Bold',
    fontWeight: '700',
    fontSize: hp(1.9),
    marginTop: hp(5),
    marginLeft: wp(7),
    opacity: 0.5,
  },
  input: {
    width: wp(28),
    height: hp(6),
    paddingLeft: wp(1),
    borderBottomWidth: hp(0.2),
    marginLeft: wp(6),
    marginTop: hp(3.6),
    color: 'rgba(12, 26, 52, 0.64)',
    //opacity: 0.5,
    //fontSize: hp(1.6),
    fontFamily: 'Rubik-Regular',
    //backgroundColor: 'red',
  },
  lastNameInput: {
    width: wp(2),
    height: hp(6),
    paddingLeft: wp(1),
    borderBottomWidth: hp(0.2),
    marginLeft: wp(6),
    marginTop: hp(3.6),
    color: 'rgba(12, 26, 52, 0.64)',
    //opacity: 0.5,
    fontSize: hp(1.6),
    fontFamily: 'Rubik-Regular',
  },
  primaryButton: {
    width: wp(44),
    height: hp(5.2),
    backgroundColor: '#0084F8',
    marginLeft: wp(51),
    borderRadius: hp(12),
    marginTop: hp(4.8),
  },
  primaryText: {
    alignSelf: 'center',
    marginTop: hp(1.4),
    color: '#FFFFFF',
    fontFamily: 'Poppins-Bold',
    fontSize: hp(1.5),
  },
  inputTextView: {width: wp(62)},
  floatLabelView: {flexDirection: 'row'},
  firstNameInput: {
    color: '#232426',
    paddingHorizontal: 10,
    fontFamily: 'Rubik-SemiBold',
    fontSize: hp(2),
    fontWeight: '400',
    marginTop: hp(1),
    marginLeft: wp(-1),
  },
  secondInputView: {width: wp(37), marginLeft: -12},
  firstLabel: {
    color: 'red',
    fontFamily: 'Rubik-Regular',
    fontSize: 4,
    fontWeight: '400',
    opacity: 0.56,
  },
  secondNameView: {
    color: '#232426',
    paddingHorizontal: 10,
    fontFamily: 'Rubik-Bold',
    fontSize: 14,
    fontWeight: '400',
    marginTop: hp(1),
    marginLeft: wp(-1),
  },
  secondLabel: {
    color: 'red',
    fontFamily: 'Rubik-Regular',
    fontSize: hp(0.2),
    fontWeight: '400',
    opacity: 0.56,
    marginLeft: wp(-2.8),
  },
});
