/* eslint-disable @typescript-eslint/no-unused-vars */
import {StyleSheet} from 'react-native';
import {
  widthPercentageToDP as wp,
  heightPercentageToDP as hp,
} from 'react-native-responsive-screen';

export default StyleSheet.create({
  topBar: {
    flex: 1,
    padding: hp(4),
    flexDirection: 'row',
    marginLeft: wp(-2),
    marginTop: hp(2),
  },
  firstBarView: {
    width: wp(12),
    height: hp(0.7),
    backgroundColor: '#0084F8',
    marginLeft: wp(2),
  },
  secondBarView: {
    width: wp(12),
    height: hp(0.7),
    backgroundColor: 'rgba(0, 0, 0, 0.07)',
    marginLeft: wp(2),
  },
  titleView: {marginLeft: wp(-68), marginTop: hp(8), width: wp(70)},
  subTitleView: {marginLeft: wp(-70), marginTop: hp(20.8), width: wp(70)},
  buttonView: {
    marginTop: hp(29),
    marginLeft: wp(29),
    flexDirection: 'row',
    position: 'absolute',
    //backgroundColor: 'red',
  },
  title: {
    width: wp(82),
    fontFamily: 'Poppins-Medium',
    fontSize: hp(3.8),
    fontWeight: '500',
    letterSpacing: hp(-0.2),
    color: '#000000',
  },
  thirdText: {
    width: wp(85),
    marginTop: hp(1),
    fontSize: hp(1.7),
    fontFamily: 'Gilroy-Bold',
    color: '#00192F',
    opacity: 0.56,
  },
  primaryButton: {
    width: wp(33),
    height: hp(5.2),
    backgroundColor: '#0084F8',
    marginLeft: wp(-18),
    borderRadius: hp(12),
    marginTop: hp(3),
  },
  primaryText: {
    alignSelf: 'center',
    marginTop: hp(1.4),
    color: '#FFFFFF',
    fontFamily: 'Poppins-Bold',
    fontSize: hp(1.5),
  },
  lightButton: {
    width: wp(33),
    height: hp(5.6),
    borderRadius: hp(10),
    marginLeft: wp(16),
    marginTop: hp(-5.4),
  },
  lightText: {
    alignSelf: 'center',
    marginTop: hp(4.4),
    color: '#0084F8',
    fontFamily: 'Poppins-Bold',
    fontSize: hp(1.4),
    marginLeft: wp(8),
  },
  footerText: {
    fontSize: hp(1.2),
    fontWeight: '600',
    width: wp(80),
    height: hp(10),
    fontFamily: 'Gilroy-SemiBold',
    marginTop: hp(89),
    marginLeft: wp(-66),
    color: '#0C1A34',
    opacity: 0.56,
  },
  slideContainer: {alignItems: 'center', width: 410, height: hp(120)},
  buttons: {
    display: 'flex',
  },
  image: {marginLeft: -230},
  slideOne: {marginTop: hp(45), position: 'absolute'},
  slideTwo: {marginTop: hp(37), position: 'absolute', marginLeft: -80},
  slideThree: {marginTop: hp(44), position: 'absolute'},
  slideFour: {marginTop: hp(36), position: 'absolute'},
  slideFive: {marginTop: hp(44), position: 'absolute'},
});
