import {StyleSheet} from 'react-native';
import {
  widthPercentageToDP as wp,
  heightPercentageToDP as hp,
} from 'react-native-responsive-screen';

export default StyleSheet.create({
  container: {flex: 1, backgroundColor: '#FFFFFF'},
  userNameView: {flexDirection: 'row', padding: hp(1.6), marginTop: hp(2)},
  userNameText: {
    fontSize: hp(2),
    fontWeight: '600',
    fontFamily: 'Poppins-SemiBold',
    color: '#000000',
    letterSpacing: -0.75,
    marginLeft: hp(1.4),
  },
  payIcon: {marginLeft: wp(54), marginTop: hp(0.2)},
  walletBalanceView: {padding: hp(1.6), marginTop: hp(2)},
  walletSecondView: {flexDirection: 'row'},
  walletText: {
    fontSize: hp(1.6),
    fontWeight: '600',
    fontFamily: 'Gilroy-SemiBold',
    color: '#00192F',
    marginLeft: wp(3.2),
  },
  eyeIcon: {marginLeft: wp(3), marginTop: hp(0.1)},
  balanceView: {flexDirection: 'row', marginTop: hp(1.8)},
  dolorText: {
    marginLeft: wp(4),
    marginTop: hp(0.6),
    color: '#000000',
    fontSize: hp(2.4),
  },
  balanceText: {
    fontSize: hp(3.4),
    paddingLeft: wp(3),
    fontFamily: 'Rubik-Regular',
    color: '#000000',
    marginLeft: wp(-1),
    marginTop: hp(0.2),
  },
  arrowIcon: {marginLeft: wp(63), marginTop: 14},
  buttonsView: {
    padding: hp(2.2),
    flexDirection: 'row',
    marginTop: hp(-0.2),
    marginLeft: wp(-1),
  },
  depositeView: {
    width: wp(30),
    height: hp(14.4),
    borderRadius: hp(2),
    //backgroundColor: '#0084F8',
  },
  payView: {
    width: wp(30),
    height: hp(14.4),
    borderRadius: hp(2),
    marginLeft: wp(2),
    backgroundColor: '#F2F6FD',
  },
  earningView: {
    width: wp(30),
    height: hp(14.4),
    borderRadius: hp(2),
    marginLeft: wp(2),
    backgroundColor: '#F2F6FD',
  },
  dollar: {alignSelf: 'center', marginTop: hp(3.6)},
  DepositeText: {
    alignSelf: 'center',
    //color: '#FFFFFF',
    fontFamily: 'Gilroy-Bold',
    fontWeight: '600',
    fontSize: hp(1.6),
    marginTop: hp(1),
  },
  fundsText: {
    marginLeft: hp(5.2),
    //color: '#FFFFFF',
    fontFamily: 'Gilroy-Bold',
    fontWeight: '600',
    fontSize: hp(1.6),
  },
  PayText: {
    alignSelf: 'center',
    color: '#0084F8',
    fontFamily: 'Gilroy-Bold',
    fontWeight: '600',
    fontSize: hp(1.6),
    marginTop: hp(1),
  },
  someOneText: {
    marginLeft: hp(4),
    color: '#0084F8',
    fontFamily: 'Gilroy-Bold',
    fontWeight: '600',
    fontSize: hp(1.6),
  },
  AddFundsText: {
    color: '#667686',
    fontFamily: 'Gilroy-Bold',
    fontWeight: '600',
    fontSize: hp(1.4),
    marginTop: hp(6),
    letterSpacing: hp(0.1),
    marginLeft: wp(7),
    alignSelf: 'center',
  },
  DashboardImage: {alignSelf: 'center', marginTop: hp(5)},
  bottomView: {
    width: wp(100),
    height: hp(10),
    backgroundColor: 'white',
    shadowColor: '#0084F8',
    shadowOpacity: 100,
    shadowRadius: 60,
    elevation: 25,
    shadowOffset: {width: 0, height: 10},
    marginTop: -88,
    flexDirection: 'row',
    justifyContent: 'space-evenly',
    borderTopLeftRadius: hp(2),
    borderTopRightRadius: hp(2),
  },
  bottomIconView: {marginTop: 25},
  firstBottomImage: {marginLeft: 2},
  secondBottomImage: {marginLeft: 32},
  firstBottomText: {color: '#101F3D', fontSize: 10, marginLeft: -5},
  secondBottomText: {color: '#101F3D', fontSize: 10, marginLeft: -7},
  thirdBottomImage: {marginLeft: 20},
  thirdBottomText: {color: '#101F3D', fontSize: 10, marginLeft: -7},
  fourthBottomImage: {marginLeft: 18},
  fourthBottomText: {color: '#101F3D', fontSize: 10, marginLeft: -5},
});
